services:
  sub2api:
    image: ghcr.io/amyrulmynin/sub2api:my-custom
    pull_policy: always
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      AUTO_SETUP: "true"
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      SERVER_MODE: "release"
      RUN_MODE: "standard"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USER: "sub2api"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_DBNAME: "sub2api"
      DATABASE_SSLMODE: "disable"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      REDIS_DB: "0"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRE_HOUR: "24"
      TOTP_ENCRYPTION_KEY: "${TOTP_ENCRYPTION_KEY}"
      TZ: "Asia/Kuala_Lumpur"
      SETUP_MIGRATION_TIMEOUT_SECONDS: "180"
    volumes:
      - sub2api_data:/app/data

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "sub2api"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "sub2api"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sub2api -d sub2api"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sub2api_data:
  postgres_data_v2:
  redis_data:
